name: Extract and Push ZIP Contents

on:
  workflow_dispatch:  # This allows you to run it manually from the Actions tab

jobs:
  extract_zip_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download ZIP from URL (or skip if uploading)
        run: |
          curl -L -o archive.zip https://github.com/extrinsicBox/KCD2-Scripting/blob/main/KCD2_Scripts.zip

      - name: Unzip Files
        run: |
          unzip my_files.zip -d temp_folder
          ls temp_folder

      - name: Move Extracted Files to Repo
        run: |
          mv temp_folder/* .
          rm -rf temp_folder

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Extracted and added files from ZIP"
          git push origin main
